# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91d46db68936de44433259abade1bc2da09a7a5d4eed7ceddafeee8fdbae2fc6c44d46c7b323bfb1e58ecfca6cac64dcfccc0905d0cffa704ca0371996db6c3e

test:
  secret_key_base: 53c4f96b92250a31ab380f1d5ab4fe499926a4f2f102af38347a44e7abd59aa80b33490847f2781bad9aa878303821e12fb6eb83314b814e3591bdc567afeb3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
